version: 0.2

phases:
  build:
    commands:
      - echo "Empaquetando el código en un archivo zip..."
      - zip -r deployment_package.zip lambda_function.py
artifacts:
  files:
    - deployment_package.zip